### ISSUE TITLE
Different triggers to start a recording

### ISSUE THREAD

**Issue by 0xboobface** [0xboobface/ctbrec#91]
Instead of starting / stopping a recording, when a model comes online / goes offline, it would be nice to support different triggers:
- [ ] model comes online / goes offline
- [ ] model has been online since x minutes (this would require a mechanism to track how long a model is online. Short discontinuities like privates, or temp. disconnection of the models connection should not reset the tracker) (suggested in #66)
- [ ] stop when recording reached a certain length (suggested in #66)
- [ ] models viewer count passes a threshold (this probably needs something like a moving average to detect, when the viewer count increases / decreases a lot) (suggested in #90 and #66)
- [ ] fire and forget (suggested in #90)

**Comment by 0xboobface** [comment]
Another suggestion from #95. This is only possible, if you know all online models. For MFC it work, but for the other sites ?!?

> RECORD AUTOMATICALLY ONLY:
```
() by continent(s)/region(s): [insert continent/region or continents/regions separated by commas]
() by country(ies): [same procedure/example above]
() by ethnic(s): [same procedure/example above]
() by age: () equal to [insert age]
           () less than [...]
           () more than [...]
           () between [...] and [...]
() if the occupation contains the keyword(s): [insert keyword(s) separated by commas]
() if the blurb contains the keyword(s): [same procedure/example above]
() if the topic contains the keyword(s): [same procedure/example above]
() if the tags contains the keyword(s): [same procedure/example above]
() if the Model is "new"
```
